name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install gcc-avr avr-libc simavr

    - name: Compile code
      run: |
        avr-gcc -mmcu=atmega328p -o main.elf main.c
        avr-objcopy -O ihex main.elf main.hex

    - name: Run simulation
      run: |
        simavr -m atmega328p -f 16000000 main.hex

